choco install 1password
choco install battle.net
choco install brave
choco install cpu-z.install
choco install crystaldiskinfo
choco install crystaldiskmark
choco install discord.install
choco install dotnet-7.0-desktopruntime
choco install dotnet-desktopruntime
choco install ds4windows
choco install epicgameslauncher
choco install gpu-z
choco install hwinfo.install
choco install itunes
choco install mpv.install
choco install msiafterburner
choco install netfx-4.6.2
choco install notepadplusplus
choco install openrgb
choco install parsec
choco install qbittorrent
choco install rockstar-launcher
choco install samsung-magician
choco install steam
choco install uplay
choco install vcredist140
choco install vlc
choco install vortex
choco install wiztree
# install thrustmaster drivers https://support.thrustmaster.com/en/product/t300rs-en/
# install ARMGDDN Browser
# install ClickMonitorDDC 